apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: victoria-metrics-prometheus
  namespace: monitoring
spec:
  allowCrossNamespaceImport: true
  instanceSelector:
    matchLabels:
      grafana: main
  uid: vm-prometheus
  datasource:
    name: "Prometheus (VictoriaMetrics)"
    type: prometheus
    access: proxy
    url: http://vmsingle-victoria-metrics.monitoring.svc.cluster.local:8428
