apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: prometheus-victoria-metrics
  namespace: monitoring
spec:
  allowCrossNamespaceImport: true
  instanceSelector:
    matchLabels:
      grafana: main
  datasource:
    name: "Prometheus (VictoriaMetrics)"
    type: prometheus
    access: proxy
    url: http://vmsingle-victoria-metrics.monitoring.svc.cluster.local:8428
